# Generated by Django 4.1 on 2023-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('surveyor', models.CharField(blank=True, max_length=50, null=True)),
                ('surveydate', models.DateTimeField(blank=True, null=True)),
                ('poicat', models.IntegerField(blank=True, null=True)),
                ('poitype', models.IntegerField(blank=True, null=True)),
                ('signupdate', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('poiname', models.CharField(blank=True, max_length=255, null=True)),
                ('poi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('img_flag', models.SmallIntegerField()),
                ('existing', models.SmallIntegerField()),
                ('egyeb_szuro', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keszpoi_teszt_bagger',
                'managed': False,
            },
        ),
    ]
