# Generated by Django 4.1 on 2023-10-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poiAPI', '0002_myimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
    ]
